In [1]:
from mxnet import nd
w = nd.arange(4).reshape((1,1,2,2))
b = nd.array([1])
data = nd.arange(9).reshape((1,1,3,3))
out = nd.Convolution(data,w,b,kernel=w.shape[2:], num_filter= w.shape[1])

print('input', data, '\n\nweight:', w, '\n\nbias', b, '\n\noutput:', out)

input 
[[[[0. 1. 2.]
   [3. 4. 5.]
   [6. 7. 8.]]]]
<NDArray 1x1x3x3 @cpu(0)> 

weight: 
[[[[0. 1.]
   [2. 3.]]]]
<NDArray 1x1x2x2 @cpu(0)> 

bias 
[1.]
<NDArray 1 @cpu(0)> 

output: 
[[[[20. 26.]
   [38. 44.]]]]
<NDArray 1x1x2x2 @cpu(0)>


In [4]:
out = nd.Convolution(data, w,b,kernel=w.shape[2:], num_filter=w.shape[1], stride=(2,2), pad=(1,1))
print('input', data, '\n\nweight:', w, '\n\nbias', b, '\n\noutput:', out)

input 
[[[[0. 1. 2.]
   [3. 4. 5.]
   [6. 7. 8.]]]]
<NDArray 1x1x3x3 @cpu(0)> 

weight: 
[[[[0. 1.]
   [2. 3.]]]]
<NDArray 1x1x2x2 @cpu(0)> 

bias 
[1.]
<NDArray 1 @cpu(0)> 

output: 
[[[[ 1.  9.]
   [22. 44.]]]]
<NDArray 1x1x2x2 @cpu(0)>


In [2]:
w = nd.arange(8).reshape((1,2,2,2))
data = nd.arange(18).reshape((1,2,3,3))

out = nd.Convolution(data, w,b,kernel=w.shape[2:], num_filter=w.shape[0]) 
print('input', data, '\n\nweight:', w, '\n\nbias', b, '\n\noutput:', out)

input 
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]]
<NDArray 1x2x3x3 @cpu(0)> 

weight: 
[[[[0. 1.]
   [2. 3.]]

  [[4. 5.]
   [6. 7.]]]]
<NDArray 1x2x2x2 @cpu(0)> 

bias 
[1.]
<NDArray 1 @cpu(0)> 

output: 
[[[[269. 297.]
   [353. 381.]]]]
<NDArray 1x1x2x2 @cpu(0)>


In [3]:
w = nd.arange(16).reshape((2,2,2,2))
data = nd.arange(18).reshape((1,2,3,3))
b = nd.array([1,2])

out = nd.Convolution(data, w,b,kernel=w.shape[2:], num_filter=w.shape[0]) 

print('input', data, '\n\nweight:', w, '\n\nbias', b, '\n\noutput:', out)

input 
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]]
<NDArray 1x2x3x3 @cpu(0)> 

weight: 
[[[[ 0.  1.]
   [ 2.  3.]]

  [[ 4.  5.]
   [ 6.  7.]]]


 [[[ 8.  9.]
   [10. 11.]]

  [[12. 13.]
   [14. 15.]]]]
<NDArray 2x2x2x2 @cpu(0)> 

bias 
[1. 2.]
<NDArray 2 @cpu(0)> 

output: 
[[[[ 269.  297.]
   [ 353.  381.]]

  [[ 686.  778.]
   [ 962. 1054.]]]]
<NDArray 1x2x2x2 @cpu(0)>


池化层(pooling)
因为卷积层每次作用在一个窗口,它对位置很敏感.池化层能够很好地缓解这个问题.它跟卷积类似,每次看一个小窗口,然后选出窗口里面最大的元素,或者平均元素作为输出

In [4]:
data = nd.arange(18).reshape((1,2,3,3))

max_pool = nd.Pooling(data=data, pool_type="max", kernel=(2,2))
avg_pool = nd.Pooling(data=data, pool_type="avg", kernel=(2,2))

print('data:', data, '\n\nmax pooling:', max_pool, '\n\navg pooling', avg_pool)

data: 
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]]
<NDArray 1x2x3x3 @cpu(0)> 

max pooling: 
[[[[ 4.  5.]
   [ 7.  8.]]

  [[13. 14.]
   [16. 17.]]]]
<NDArray 1x2x2x2 @cpu(0)> 

avg pooling 
[[[[ 2.  3.]
   [ 5.  6.]]

  [[11. 12.]
   [14. 15.]]]]
<NDArray 1x2x2x2 @cpu(0)>


In [4]:
import sys
sys.path.append('..')
from d2lzh import  utils
from mxnet import nd

batch_size = 256
train_data, test_data = utils.load_data_fashion_mnist(batch_size)
print(train_data)

In [5]:
import mxnet as mx

try:
    ctx = mx.gpu()
    _ = nd.zeros((1,), ctx = ctx)
except:
    ctx = mx.cpu()

ctx
print(_)


[0.]
<NDArray 1 @gpu(0)>


In [6]:
weight_scale = .01
num_outputs =10


#output channels = 20, kernel = (5,5)
W1 = nd.random_normal(shape=(20,1,5,5), scale=weight_scale, ctx=ctx)
b1 = nd.zeros(W1.shape[0],ctx=ctx)

#output channels = 50, kernel = (3,3)
W2 = nd.random_normal(shape=(50,20,3,3), scale=weight_scale, ctx=ctx)
b2 = nd.zeros(W2.shape[0],ctx=ctx)

#output  dim=128
W3 = nd.random_normal(shape=(1250,128), scale=weight_scale, ctx=ctx)
b3 = nd.zeros(W3.shape[1],ctx=ctx)

#output dim=10
W4 = nd.random_normal(shape=(W3.shape[1],10), scale=weight_scale, ctx=ctx)
b4 = nd.zeros(W4.shape[1],ctx=ctx)

params = [W1,b1, W2,b2, W3,b3, W4,b4]
for param in params:
    param.attach_grad()

In [7]:
def net(X):
    X=X.as_in_context(W1.context)
    #第一层卷积
    h1_conv = nd.Convolution(
            data=X, weight=W1, bias=b1, kernel=W1.shape[2:], num_filter=W1.shape[0])
    h1_activation = nd.relu(h1_conv)
    h1 = nd.Pooling(
            data=h1_activation, pool_type="max", kernel=(2,2), stride=(2,2))
        
    #第二层卷积
    h2_conv = nd.Convolution(
            data=h1, weight=W2, bias=b2, kernel=W2.shape[2:], num_filter=W2.shape[0])
    h2_activation = nd.relu(h1_conv)
    h2 = nd.Pooling(
            data=h2_activation, pool_type="max", kernel=(2,2), stride=(2,2))    
    h2 = nd.flatten(h2)
        
    #第一层全连接
    h3_linear = nd.dot(h2, W3)+ b3
    h3 = nd.relu(h3_linear)
        
    #第二层全连接
    h4_linear = nd.dot(h3,W4) +b4
    

    print('1st conv block:', h1.shape)
    print('2nd conv block:', h2.shape)
    print('1st dense:', h3.shape)
    print('2nd dense', h4_linear.shape)
    print('output:', h4_linear)
    return h4_linear 

In [8]:
for data,  _  in train_data:
    net(data)
    break

MXNetError: [11:15:42] c:\jenkins\workspace\mxnet\mxnet\src\operator\tensor\./dot-inl.h:1240: Check failed: L[!Ta].Size() == R[Tb].Size() (2880 vs. 1250) : dot shape error: [256,2880] X [1250,128]